wandb_version: 1

data:
  desc: null
  value: ../datasets/cifar10
dataset:
  desc: null
  value: cifar10
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.025
learning_rate_min:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0003
report_freq:
  desc: null
  value: 50
gpu:
  desc: null
  value: 0
epochs:
  desc: null
  value: 100
init_channels:
  desc: null
  value: 16
layers:
  desc: null
  value: 8
model_path:
  desc: null
  value: saved_models
cutout:
  desc: null
  value: false
cutout_length:
  desc: null
  value: 16
cutout_prob:
  desc: null
  value: 1.0
save:
  desc: null
  value: ../experiments/nasbench201/cifar10/search-exp-20240531-135227-2-7047
seed:
  desc: null
  value: 2
grad_clip:
  desc: null
  value: 5
train_portion:
  desc: null
  value: 0.5
unrolled:
  desc: null
  value: false
arch_learning_rate:
  desc: null
  value: 0.0003
arch_weight_decay:
  desc: null
  value: 0.001
perturb_alpha:
  desc: null
  value: none
epsilon_alpha:
  desc: null
  value: 0.3
wandb:
  desc: null
  value: true
nasbench:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717163548
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
